### ISSUE TITLE
Assertion failed! (LATEST BUILD) SpritePolygon Creation => pressing right arrow

### ISSUE THREAD

**Issue by aismann** [axys1/axys#231]
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: ...-x-master\.build\bin\cpp-tests\Debug\cpp-tests.exe
File: D:\_____EGNX\EGNX_1007\EGNX_1007\en...\CCAutoP...gon.cpp
Line: 260

Expression: sv != 0 && sv != 15

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by aismann** [comment]
some more hint (changing the resourceSize back to:
 static Size resourceSize(960, 640);    <<<<<<<<<<<<<<<<<   works!!!
 static Size resourceSize(1280, 720);  <<<<<<<<<<<<<<<<<   failed

**Comment by halx99** [comment]
Yes, I have checked the official v4, also have same problem

**Comment by aismann** [comment]
@halx99 Please remove the label: "needs-confirm"

**Comment by aismann** [comment]
Maybe a hint on the documentation is helpful? 
=> Rect have to be adapt to the 2.0/"ContentScaleFactor()"
