### ISSUE TITLE
Android: using the native Android Game Development Kit (AGDK) directly for Android platforms

### ISSUE THREAD

**Issue by aismann** [axys1/axys#439]
Android Game Development Kit  (https://developer.android.com/games)
The Android Game Development Kit (AGDK) is a full range of tools and libraries to help you develop, optimize, launch, and iterate on high quality Android games.

Maybe a wrapper around the AGDK is needed to have cross platform compatibility

**Comment by halx99** [comment]
Should be a large work

**Comment by tallesborges** [comment]
I agree with the implementation of the AGDK, I have a plan to analyze it soon.

**Comment by aismann** [comment]
Help for your development workflow
If you're working with game engine sources to create the best Android experience, or using an unmodified game engine as a turnkey solution, we can help.
https://developer.android.com/games#choose-your-workflow
