### ISSUE TITLE
[Refactor] Improve enum defination rules

### ISSUE THREAD

**Issue by halx99** [axys1/axys#661]
When all characters of a enum symbol are uppercase, some times, will confilcit with system macro definations, such as:

- `OS_WINDOWS` conflicit with `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\Shlwapi.h`
- `ALPHA_MASK` confilcit with `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\gdipluspixelformats.h`

Sugesstion solution, change all enum to like class name, such as:

`ALPHA_MASK` to `AlphaMask`

**Comment by DelinWorks** [comment]
since it's not exposed to the user, maybe `PARTICLE_ALPHA_MASK` is better?

**Comment by DelinWorks** [comment]
I see why now. but `AlphaMask` feels out of touch

![image](https://user-images.githubusercontent.com/45469625/174105274-d5cadde9-acb4-43f3-9e08-1de1af4c16ab.png)

**Comment by halx99** [comment]
> I see why now. but `AlphaMask` feels out of touch
> 
> ![image](https://user-images.githubusercontent.com/45469625/174105274-d5cadde9-acb4-43f3-9e08-1de1af4c16ab.png)

It's touch to c# code.
