### ISSUE TITLE
FairGUI 2022.1.0 (released on February 14, 2022) 

### ISSUE THREAD

**Issue by aismann** [axys1/axys#664]
2022.1.0 (released on February 14, 2022)
Maybe an hint to the license is also a good idea  (third party readme)?

**Comment by halx99** [comment]
Add a `README.md` file to folder `extensions` to describe all extensions maybe better

**Comment by aismann** [comment]
> Add a `README.md` file to folder `extensions` to describe all extensions maybe better

Yes good idea.
But an "one" page where you can get all information about the "licenses" was the goal of the ['Upstream-Version-License'] page.
