### ISSUE TITLE
Replace Vector push_back() vs emplace_back()

### ISSUE THREAD

**Issue by aismann** [axys1/axys#762]
push_back and emplace_back in C++
Push_back: Push_back adds a new element at the end. It first creates a temporary object by calling a constructor.

Emplace_back: It also Inserts a new element at the end. It does not create a temporary object. The object is directly created in the vector. Due to this, the efficiency is increased.

The difference in the efficiency of push_back and emplace_back depends on the type of our vector. If the vector is a built-in type, there is no difference between the efficiency of push_back and emplace_back. If the vector type is class or struct, emplace_back is more efficient than push_back.

![image](https://user-images.githubusercontent.com/8652787/180176355-9350821f-e72f-420b-a3ab-a6d9a41d58a0.png)

see also:
https://www.codingninjas.com/codestudio/library/vector-push_back-vs-emplace_back#:~:text=Push_back%3A%20Push_back%20adds%20a%20new%20element%20at%20the,vector.%20Due%20to%20this%2C%20the%20efficiency%20is%20increased.

**Comment by DelinWorks** [comment]
Good job! this would improve mesh generation speed since vertices get added with `emplace_back` rather than `push_back` I like it! it would be cool if `IndexArray` gets this change, but I fear that POD-like data `(i.e. floats, integers, chars)` don't get this boost because they are not constructed or rather they are simple types, unlike a custom type the user created. I really don't know

**Comment by DelinWorks** [comment]
> The difference in the efficiency of push_back and emplace_back depends on the type of our vector. If the vector is a built-in type, there is no difference between the efficiency of push_back and emplace_back. If the vector type is class or struct, emplace_back is more efficient than push_back.

Oh! sorry I didn't think you mentioned it there

**Comment by aismann** [comment]
Should we replying?

**Comment by DelinWorks** [comment]
do you mean the `Vector` class with an uppercase V that holds references? or what array class exactly?

**Comment by aismann** [comment]
> do you mean the `Vector` class with an uppercase V that holds references? if not then what array class exactly?
> 
> keep in mind that users will not adapt to this change and will instead use the default insertion method.

We change the axis engine. What users doing on here own sources is not the goal of this issue.

**Comment by aismann** [comment]
Have axis some tests which can show an performance boost?

**Comment by DelinWorks** [comment]
> > do you mean the `Vector` class with an uppercase V that holds references? if not then what array class exactly?
> > keep in mind that users will not adapt to this change and will instead use the default insertion method.
> 
> We change the axis engine. What users doing on here own sources is not the goal of this issue. I belive evey repace is a good idea on the axis engine sources

yeah you're right, should always consider that!

**Comment by aismann** [comment]
Replace push_back() vs emplace_back() on axis\core\ #781

**Comment by aismann** [comment]
old: push_back:
![image](https://user-images.githubusercontent.com/8652787/183305711-97d590d5-1f9e-4be6-afaf-a14b03bfeb30.png)
new: emplace_back:
![image](https://user-images.githubusercontent.com/8652787/183305812-dfefc2af-e87f-48c4-b67e-35019473814f.png)

**Comment by aismann** [comment]
'extension' has also some potential:
Which folder should be NOT changed?
![image](https://user-images.githubusercontent.com/8652787/183340415-12a74ce0-6e5e-49be-97ab-9b2b12bf1858.png)

**Comment by halx99** [comment]
The fiarygui, ImGui, Live2D, spine should be NOT changed

**Comment by aismann** [comment]
> The fiarygui, ImGui, Live2D, spine should be NOT changed

What about DragonBones? Can be adapt?

**Comment by halx99** [comment]
You aslo can skip `DragonBones` since it stop maintenance 4 years.

**Comment by aismann** [comment]
Can be closed after merge.

**Comment by aismann** [comment]
with the extensions i got some more sprites:
![image](https://user-images.githubusercontent.com/8652787/183420610-9b9b2605-98d4-4690-9709-a4b38768cb1f.png)
