### ISSUE TITLE
[PROPOSAL] Organization name change

### ISSUE THREAD

**Issue by DelinWorks** [axys1/axys#784]
maybe the organization name of this repo can be set to something more explanatory like `axys-game-engine` or `axys-engine` rather than `axys1`?
it would make it more professional.

**Comment by halx99** [comment]
That makes the url too long, and all docs urls also need sync again in all sources, so we need a stable org name before change it

**Comment by halx99** [comment]
> how about we name it a name that's independent of the engine name? something like the company you're in `bytedance` or something! or it doesn't matter we can leave it like that.

Corret choice
