### ISSUE TITLE
Wrong libjpeg version for Mac included

### ISSUE THREAD

**Issue by pietpukkel** [axys1/axys#788]
The now included precompiled binary for Mac of libjpeg is version 90, whereas the headerfiles are for version 80 (leading to an error when performing the Texture2D test in cpp_test). I've recompiled with version 80 and will send a pull request.

**Comment by aismann** [comment]
@halx99 
Can it closed?

**Comment by halx99** [comment]
Refer to https://github.com/axys1/buildware/pull/6

**Comment by pietpukkel** [comment]
Can be closed but please remove the Mac libraries I asked to be pulled earlier and replace them with ones build  from buildware after I've included glsl-optimizer too.

**Comment by halx99** [comment]
> Can be closed but please remove the Mac libraries I asked to be pulled earlier and replace them with ones build from buildware after I've included glsl-optimizer too.

Sure
