### ISSUE TITLE
Fork of this project receiving workflow notifications for failed jobs

### ISSUE THREAD

**Issue by rh101** [axys1/axys#794]
@halx99 I synced my fork of this project today, and now I'm suddenly getting notifications like this:

![image](https://user-images.githubusercontent.com/8603230/184060851-9804deba-5415-4a46-be76-76de7a6d58dd.png)

Has something recently changed in the settings of this repository? I shouldn't be receiving these notifications since they're being run on this repository, not the fork I've created.  I'll see if there's a setting in the fork that I need to turn off, but this has never happened before.

**Comment by halx99** [comment]
Refer to #793

**Comment by rh101** [comment]
No worries. I'll close this issue since the other one covers it.
