### ISSUE TITLE
link prebuilt for project   => get Error:	LNK1181	cannot open input file 'jpeg-static.lib'	

### ISSUE THREAD

**Issue by aismann** [axys1/axys#809]
Wrong .../jepg/... path
![image](https://user-images.githubusercontent.com/8652787/185454269-485c6718-60dd-4011-9bb6-0b9e29ad41be.png)
adapt it .../jpeg-**turbo**/... and works now:
![image](https://user-images.githubusercontent.com/8652787/185454533-55639bc0-d32a-4c94-aec8-e8a7560e824d.png)

**Comment by halx99** [comment]
Fixed by https://github.com/axys1/axys/commit/44e98f9c41de3b2c86a548e90bac8aaa40f9e1b2
