### ISSUE TITLE
Replace 'cocos2d' with 'axys' on AXLOG(WARN) like: AXLOG("cocos2d: SpriteFrameCache: Frame '%s' isn't found", name.data());

### ISSUE THREAD

**Issue by aismann** [axys1/axys#825]
Replace 'cocos2d' with 'axys' on:
AXLOG(WARN) like:      AXLOG("cocos2d: SpriteFrameCache: Frame '%s' isn't found", name.data());

found 100:
![image](https://user-images.githubusercontent.com/8652787/187376195-90dfaefb-7d31-436d-8f1b-c5fb89639a4d.png)

**Comment by aismann** [comment]
AX:  or axys: or AXYS:
@halx99 what should be used?
 => axys or AXYS could be found easier with any automated scripts

**Comment by aismann** [comment]
> AX: or axys: or AXYS: @halx99 what should be used? => axys or AXYS could be found easier with any automated scripts

@halx99 
Can you give me a proposal plz?

**Comment by halx99** [comment]
`axys` is ok.
