### ISSUE TITLE
[feature] Support for tvOS

### ISSUE THREAD

**Issue by paulocoutinhox** [axys1/axys#826]
Hi,

Can you add support for tvOS and tvOS simulator?

Example:
- https://github.com/xpams/cocos2d-x-for-tvOS
- https://discuss.cocos2d-x.org/t/appletv-support/25416
- https://github.com/hawkwood/cocos2dx-helloWorld-tvOS
- https://github.com/SonarSystems/cocos2dx-helloWorld-tvOS/tree/master/Samples
- https://discuss.cocos2d-x.org/t/building-for-the-new-appletv-tvos/23758/84

Thanks.

**Comment by paulocoutinhox** [comment]
Im trying to add support to my project and post here all the diffs.


#### AppController.mm

```
#if not TARGET_OS_TV
_viewController.wantsFullScreenLayout = YES;
#endif
```

```
#if not TARGET_OS_TV
    [[UIApplication sharedApplication] setStatusBarHidden:true];
#endif
```

#### RootViewController.mm

```
#if not TARGET_OS_TV
    [eaglView setMultipleTouchEnabled:NO];
#endif
```

#### CMakeLists.txt

- Remove CoreMotion framework link (not available for tvOS): `CoreMotion is not available when building for tvOS Simulator.`
- Remove WebKit framework link (not available for tvOS): `WebKit is not available when building for tvOS Simulator.`

#### LaunchScreen

- iOS launch screen is not compatible with tvOS: `/proj.ios_mac/ios/LaunchScreen.storyboard iOS storyboards do not support target device type "tv".`

#### Linkage

**libbz2.tdb** need be linked with Apple TV version:

`ld: building for tvOS Simulator, but linking in .tbd built for iOS, file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk/usr/lib/libbz2.tbd' for architecture arm64`

#### Im putting the assets as attachment

[tv-assets.zip](https://github.com/axys1/axys/files/9481544/tv-assets.zip)

**Comment by paulocoutinhox** [comment]
Im near to finish the port, but has a problem:

```
#ifndef __ARM_FP
#error "NEON intrinsics not available with the soft-float ABI. Please use -mfloat-abi=softfp or -mfloat-abi=hard"
#else
```

on `arm_neon.h` file.

I tried add the flags:

```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mfloat-abi=softfp")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mfloat-abi=softfp")
```

But the same error happens.

What to do in this case?

**Comment by paulocoutinhox** [comment]
I found a solution disabling it on `thirdparty/astc/CMakeLists.txt` when is tvOS

**Comment by paulocoutinhox** [comment]
Hi,

Can you add libs for AppleTV and Apple TV Simulator in prebuilt folders? Only have for ios.

```
ld: in /Users/paulo/Developer/workspaces/cpp/axys/thirdparty/openssl/prebuilt/ios/libcrypto.a(libcrypto-lib-aes_cfb.o), building for tvOS Simulator, but linking in object file built for iOS Simulator, for architecture x86_64
```

Example:

<img width="151" alt="image" src="https://user-images.githubusercontent.com/395096/188252193-ad07be77-0d69-4cea-bcf6-6aa0b6037911.png">

**Comment by halx99** [comment]
Needs modify https://github.com/axys1/buildware

**Comment by paulocoutinhox** [comment]
@halx99 https://github.com/axys1/buildware/pull/7
