### ISSUE TITLE
Please add:  'Optick' a C++ Profiler For Games   => https://github.com/bombomby/optick

### ISSUE THREAD

**Issue by aismann** [axys1/axys#845]
https://github.com/bombomby/optick 

This example shows the profiling of 'SpritePolygonTestPerformance'

![image](https://user-images.githubusercontent.com/8652787/188329174-d8596b0b-d879-410c-97f9-ae71dadc97e8.png)

**Comment by halx99** [comment]
Add to where?

**Comment by aismann** [comment]
add it to the  axys CMake options like
AX_ENABLE_PROFILING true/false

if `true` add the dlls, libs and src to the at least windows build

**Comment by aismann** [comment]
Closed it.
Make a Q&A. Its better.
How can I profile axys? #847
