### ISSUE TITLE
Xcode project set ARC to on by default

### ISSUE THREAD

**Issue by qoozta** [axys1/axys#851]
- axys version: ba7a86c
- devices test on: iOS arm64
- developing environments
   - Xcode version: 14.0 RC (14A309)

Steps to Reproduce:

1.  Generate Xcode project using command.
2. Build cpp_tests.

This commit added ARC build settings and switched to ON, so the manual release of any object will trigger compile error.

**Comment by paulocoutinhox** [comment]
This was fixed here: https://github.com/axys1/axys/pull/852
