### ISSUE TITLE
Physics3D Test in cpp-tests fails if boss.c3b is replaced by boss.obj

### ISSUE THREAD

**Issue by cchuicchui** [axys1/axys#861]
- axys version: Downloaded on 2022-09-22
- devices test on: one SE3 simulator iOS 15.4
- developing environments
   - NDK version: NA
   - Xcode version: 13.3.1
   - VS/msvctools version: NA
   - cmake version: Latest
Steps to Reproduce:

1.  In bool Physics3DCollisionCallbackDemo::init(),

Change
std::vector trianglesList = Bundle3D::getTrianglesList("MeshRendererTest/boss.c3b");
to
std::vector trianglesList = Bundle3D::getTrianglesList("MeshRendererTest/boss.obj");

Change
auto sprite = Sprite3D::create("MeshRendererTest/boss.c3b");
to
auto sprite = Sprite3D::create("MeshRendererTest/boss.obj", "MeshRendererTest/boss.png");

2.    Compile cpp-tests on iPhone simulator then run

3.    Goto Physics3D Test (sub-test 4) then throw an item by clicking the screen

4.    You will see the model image distorted

5.    Two images (before image distorted and after image distorted) are uploaded
<img width="895" alt="Screenshot 2022-09-22 at 3 56 48 PM" src="https://user-images.githubusercontent.com/39337211/191691176-529ceb58-5686-4b10-a468-c7308a9b223b.png">

<img width="896" alt="Screenshot 2022-09-22 at 3 57 00 PM" src="https://user-images.githubusercontent.com/39337211/191691228-4d16d1b7-5921-4d85-88a0-3502a48e75f4.png">

**Comment by aismann** [comment]
@cchuicchui 
Plz create an own (sub)test for this issue and PR
4.1 c3b 
4.2 obj

**Comment by aismann** [comment]
@halx99 
is 'obj' format supported?
if Yes: set Label:
- Coccos2dx all
- bug

**Comment by aismann** [comment]
@halx99 
I got the same behavior.

**Comment by cchuicchui** [comment]
I just tested the problematic code in cocos2d-x in v3.17.2 and there is no problem in v3.17.2. So this problem is unique in cocos2d-x in v4.

As a result, I believe 'obj' format is supported and this is a bug.

**Comment by aismann** [comment]
Adapt cpp-tests (Screenshot from Windows OS)
![image](https://user-images.githubusercontent.com/8652787/191913319-8afab92a-7dfd-46f2-80ec-50a4732535c3.png)
![image](https://user-images.githubusercontent.com/8652787/191913418-d3e91edb-38d0-4713-9102-9a912fcfc3a8.png)

**Comment by halx99** [comment]
Plz help check does the branch `fix-861` this issue

**Comment by aismann** [comment]
@halx99 
Good work!
